robot_radius: 0.2

obstacle_range: 2.0
raytrace_range: 3.5
#footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]
footprint_inflation: 0.15

inflation_radius: 0.35
cost_scaling_factor: 0.55

max_obstacle_height: 0.8

observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
